# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Generate MV info

on:
  push:
    branches: [ master ]
    paths:
      - 'playlist/*.m3u8'
      - 'scripts/generate_mv_info.py'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
        
    - name: Generate MV info
      run: |
        # 生成MV信息
        python scripts/generate_mv_info.py
        
    - name: Push changes
      run: |
        git config --global user.email nomeqc@gmail.com
        git config --global user.name Fallrainy
        git add playlist cover playlist.json
        git commit -m "Update"
        # 暂存当前正在进行的工作
        git stash
        git pull --rebase origin ${GITHUB_REF_NAME}
        git push origin ${GITHUB_REF_NAME}
        git tag ${{ env.new_tag }}
        git push origin ${{ env.new_tag }}
        
